<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.10.8 on win32)" generated="20230330 19:07:23.528" rpa="false" schemaversion="3">
<suite id="s1" name="Api" source="D:\python\xm_git\testcases\api\api.robot">
<kw name="login_miss" type="SETUP">
<msg timestamp="20230330 19:07:44.705" level="FAIL">No keyword with name 'login_miss' found. Did you try using keyword 'BuiltIn.Log' and forgot to use enough whitespace between keyword and arguments?</msg>
<status status="FAIL" starttime="20230330 19:07:44.705" endtime="20230330 19:07:44.705"/>
</kw>
<test id="s1-t1" name="根据用户状态查询" line="114">
<tag>接口测试</tag>
<status status="FAIL" starttime="20230330 19:07:44.705" endtime="20230330 19:07:44.706">Parent suite setup failed:
No keyword with name 'login_miss' found. Did you try using keyword 'BuiltIn.Log' and forgot to use enough whitespace between keyword and arguments?</status>
</test>
<status status="FAIL" starttime="20230330 19:07:23.531" endtime="20230330 19:07:44.708">Suite setup failed:
No keyword with name 'login_miss' found. Did you try using keyword 'BuiltIn.Log' and forgot to use enough whitespace between keyword and arguments?</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">接口测试</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Api">Api</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230330 19:07:44.701" level="ERROR">Error in file 'D:\python\xm_git\testcases\api\api.robot' on line 2: Importing library 'pylib.api_def' failed: ConnectTimeout: HTTPConnectionPool(host='192.168.120.2', port=8090): Max retries exceeded with url: /labUser/getUserByStates?states=0&amp;pageNum=1&amp;pageSize=10 (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPConnection object at 0x000001E9CCEFE350&gt;, 'Connection to 192.168.120.2 timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "D:\python\xm_git\pylib\api_def.py", line 197, in &lt;module&gt;
    getUserBystates("0")
  File "D:\python\xm_git\pylib\api_def.py", line 193, in getUserBystates
    r = s.get(url=url + "/labUser/getUserByStates", params=data)
  File "D:\python\python\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "D:\python\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\python\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
PYTHONPATH:
  D:\python\xm_git
  D:\python\python\Scripts\robot.exe
  D:\python\python\python310.zip
  D:\python\python\DLLs
  D:\python\python\lib
  D:\python\python
  D:\python\python\lib\site-packages</msg>
</errors>
</robot>
